trigger:
  branches:
    include:
      - main

variables:
  imageName: 'my-java-app'
  dockerRegistryServiceConnection: 'ACR-Service-Connection'
  acrLoginServer: 'mygreensappacr.azurecr.io'
  containerRegistry: 'mygreensappacr'
  azureSubscription: 'AzureRM-AKS-Connection'
  aksCluster: 'mygreensappaks'
  aksResourceGroup: 'MyGreensApp-RG'
  namespace: 'default'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build_Java
    steps:
    - checkout: self

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        mavenVersionOption: 'Default'

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: DeployToAKS
    environment: 'aks-env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Kubernetes@1
            displayName: Set AKS context
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: $(azureSubscription)
              azureResourceGroup: $(aksResourceGroup)
              kubernetesCluster: $(aksCluster)
              command: 'login'

          - task: KubernetesManifest@0
            inputs:
              action: deploy
              kubernetesServiceConnection: $(azureSubscription)
              manifests: |
                k8s/deployment.yaml
                k8s/service.yaml
              containers: |
                $(acrLoginServer)/$(imageName):$(Build.BuildId)
